fixes

diff --git a/.github/workflows/build-push.yaml b/.github/workflows/build-push.yaml
--- a/.github/workflows/build-push.yaml
+++ b/.github/workflows/build-push.yaml
@@ -1,4 +1,4 @@
-name: Build Ubuntu Cloud Image
+name: Build, Test, and Push Multi-arch Ubuntu Cloud Image
 
 on:
   push:
@@ -9,6 +9,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    timeout-minutes: 120
     strategy:
       matrix:
         arch: [amd64, arm64]
@@ -21,43 +22,49 @@ jobs:
       with:
         version: '1.9.1'
 
-    - name: Install QEMU
+    - name: Setup OPA
+      uses: open-policy-agent/setup-opa@v2
+      with:
+        version: latest
+
+    - name: Install QEMU and dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y qemu-system-x86 qemu-system-arm qemu-utils
+        sudo apt-get install -y qemu-efi-aarch64
+        sudo apt-get install -y cloud-image-utils
 
-    - name: Debug Environment
+    - name: Verify QEMU installations
       run: |
         qemu-system-x86_64 --version
         qemu-system-aarch64 --version
-        ls -l /usr/bin/qemu*
-        lscpu
-        free -h
-        df -h
+
+    - name: Verify QEMU EFI file for ARM64
+      run: |
+        if [ -f "/usr/share/qemu-efi-aarch64/QEMU_EFI.fd" ]; then
+          echo "QEMU EFI file for ARM64 exists."
+        else
+          echo "QEMU EFI file for ARM64 is missing!"
+          exit 1
+        fi
 
     - name: Packer Init
       run: packer init .
-
+      env:
+        PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
+  
     - name: Packer Validate
-      run: packer validate .
+      run: packer validate -var "current_arch=${{ matrix.arch }}" .
 
     - name: Packer Build
       env:
         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
+        PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
       run: |
-        PACKER_LOG=1 PACKER_LOG_PATH="packer_log.txt" packer build \
-          -debug \
-          -on-error=abort \
-          -var "arch=${{ matrix.arch }}" \
+        PACKER_LOG=1 packer build \
+          -var "current_arch=${{ matrix.arch }}" \
           -var "ssh_password=$SSH_PASSWORD" \
           .
-
-    - name: Upload Packer Log
-      uses: actions/upload-artifact@v2
-      if: always()
-      with:
-        name: packer-log-${{ matrix.arch }}
-        path: packer_log.txt
 
     - name: Generate OPA Input
       run: |
